export const CHANGE_SYMBOL_SET = 'CHANGE_SYMBOL_SET';
export const CHANGE_ENTITY = 'CHANGE_ENTITY';
export const CHANGE_ENTITY_TYPE = 'CHANGE_ENTITY_TYPE';
export const CHANGE_ENTITY_SUB_TYPE = 'CHANGE_ENTITY_SUB_TYPE';
export const INITIALIZE = 'INITIALIZE';
export const SET_SYMBOL_FROM_SIC = 'SET_SYMBOL_FROM_SIC';
export const CHANGE_AMPLIFIER = 'CHANGE_AMPLIFIER';
