export const CHANGE_SYMBOL_SET = 'CHANGE_SYMBOL_SET';
export const CHANGE_ENTITY = 'CHANGE_ENTITY';
export const CHANGE_ENTITY_TYPE = 'CHANGE_ENTITY_TYPE';
export const CHANGE_ENTITY_SUB_TYPE = 'CHANGE_ENTITY_SUB_TYPE';

