export const SET_DEBUG_MODE = 'SET_DEBUG_MODE';
export const SET_CIVILIAN_FRAMES_MODE = 'SET_CIVILIAN_FRAMES_MODE';
export const SET_ALTERNATE_AMPLIFIERS_MODE = 'SET_ALTERNATE_AMPLIFIERS_MODE';
export const SET_SYMBOL_SET = 'SET_SYMBOL_SET';
export const SET_CONTEXT = 'SET_CONTEXT';
export const SET_STANDARD_IDENTIY = 'SET_STANDARD_IDENTITY';
export const SET_STATUS = 'SET_STATUS';
export const SET_HQTFDUMMY = 'SET_HQTFDUMMY';
export const SET_AMPLIFIER = 'SET_AMPLIFIER';
export const SET_AMPLIFIER_DESCRIPTOR = 'SET_AMPLIFIER_DESCRIPTOR';
export const SET_ENTITY = 'SET_ENTITY';
export const SET_ENTITY_TYPE = 'SET_ENTITY_TYPE';
export const SET_ENTITY_SUB_TYPE = 'SET_ENTITY_SUB_TYPE';
export const SET_MODIFIER_ONE = 'SET_MODIFER_ONE';
export const SET_MODIFIER_TWO = 'SET_MODIFER_TWO';

