export const SET_DEBUG_MODE = "SET_DEBUG_MODE";
export const SET_CIVILIAN_FRAMES_MODE = "SET_CIVILIAN_FRAMES_MODE";
export const SET_ALTERNATE_AMPLIFIERS_MODE = "SET_ALTERNATE_AMPLIFIERS_MODE";
export const SET_SYMBOL_SET = "SET_SYMBOL_SET";
